all:
	g++ mazeSolverParallel.cpp -lpthread -o runParallel
	./runParallel sample_mazes/161_161.txt
	./runParallel sample_mazes/2001_2001.txt
	./runParallel sample_mazes/10001_10001.txt
	./runParallel sample_mazes/14001_14001.txt

161:
	g++ mazeSolverParallel.cpp -lpthread -o runParallel
	./runParallel sample_mazes/161_161.txt

2001:
	g++ mazeSolverParallel.cpp -lpthread -o runParallel
	./runParallel sample_mazes/2001_2001.txt

10001:
	g++ mazeSolverParallel.cpp -lpthread -o runParallel
	./runParallel sample_mazes/10001_10001.txt

14001:
	g++ mazeSolverParallel.cpp -lpthread -o runParallel
	./runParallel sample_mazes/14001_14001.txt

clean:
	rm runParallel
